
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/run/media/miguel/Data/User/Sem_SO/fkinTkinter/diagnostico_so/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("668x528")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 528,
    width = 668,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    334.0,
    50.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    156.0,
    157.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    454.0,
    157.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    194.5,
    225.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D5D5D5",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=112.0,
    y=207.0,
    width=165.0,
    height=35.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    492.5,
    225.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D5D5D5",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=410.0,
    y=207.0,
    width=165.0,
    height=35.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=75.0,
    y=459.0,
    width=207.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=401.0,
    y=459.0,
    width=207.0,
    height=40.0
)

canvas.create_rectangle(
    63.0,
    278.0,
    620.0,
    438.0,
    fill="#EEE8B7",
    outline="")

my_label = canvas.create_text(
    63.0,
    278.0,
    anchor="nw",
    text="test",
    fill="#000000",
    font=("JetBrainsMonoRoman Regular", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
